kind: Deployment
apiVersion: apps/v1
metadata:
  name: efs-provisioner3
spec:
  selector:
    matchLabels:
      app: efs-provisioner3
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: efs-provisioner3
    spec:
      containers:
        - name: efs-provisioner3
          image: quay.io/external_storage/efs-provisioner:v0.1.0
          env:
            - name: FILE_SYSTEM_ID
              value: fs-0b78f2da
            - name: AWS_REGION
              value: ap-south-1
            - name: PROVISIONER_NAME
              value: lw-course/aws-efs3
          volumeMounts:
            - name: pv-volume
              mountPath: /persistentvolumes
      volumes:
        - name: pv-volume
          nfs:
            server:  fs-0b78f2da.efs.ap-south-1.amazonaws.com
            path: /